### ISSUE TITLE
Creating utility meter for HA

### ISSUE THREAD

**Issue by Spookster** [dehsgr/node-red-contrib-alphaess#18]
Im trying (and failing) to work out how to create a utility meter that HA will accept using the nodes
Its opviou7sly up and running and I have values in HA, but its just that last step to create a meter that the energy page will accept.
Any hints or clues? TIA

```
# # Test
nodered_utility_meter_daily_grid_power_import:
  source: sensor.alpha_import
  cycle: daily
  name: "Node Red UTILITY METER Daily Total Grid Import"
  unique_id: "nodered_utility_meter_daily_grid_power_import"
  offset: 0
  delta_values: false
  net_consumption: false
```

![image](https://github.com/user-attachments/assets/a9ff392c-7519-45ba-9b10-72dcd7ee4435)
